DROP TABLE TBL_USERS;
DROP TABLE TBL_HOTELS;
DROP TABLE TBL_ROOMS_GENERAL;
DROP TABLE TBL_ROOMS_SPECIFIC;
DROP TABLE TBL_BOOKINGS;
--DROP TABLE TBL_ROOMS;
DROP TABLE TBL_PEAK;
DROP TABLE TBL_PIN;


CREATE TABLE TBL_USERS (
	USER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	PRIMARY KEY(USER_ID),
	SURNAME VARCHAR(20) NOT NULL,
	OTHERNAME VARCHAR(20) NOT NULL,
	ROLE VARCHAR(10) NOT NULL CHECK (ROLE IN('CUSTOMER', 'MANAGER', 'OWNER')),
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	EMAIL LONG VARCHAR NOT NULL,
	DETAILS LONG VARCHAR NOT NULL,
	PIN INTEGER NOT NULL
);

ALTER TABLE TBL_USERS
ADD DETAILS LONG VARCHAR;

ALTER TABLE TBL_USERS
ADD PIN INTEGER;

CREATE TABLE TBL_HOTELS (
	HOTEL_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	PRIMARY KEY(HOTEL_ID),
	NAME VARCHAR(20) NOT NULL,
	CITY VARCHAR(20) NOT NULL,
	MANAGERID INTEGER NOT NULL,
	OWNERID INTEGER NOT NULL,
	DETAILS LONG VARCHAR NOT NULL,
	
	FOREIGN KEY (MANAGERID) REFERENCES TBL_USERS(USER_ID),
	FOREIGN KEY (OWNERID) REFERENCES TBL_USERS(USER_ID)
);

CREATE TABLE TBL_ROOMS_GENERAL(
	ROOM_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	PRIMARY KEY(ROOM_ID),
	ROOM_TYPE VARCHAR(10) NOT NULL CHECK (ROOM_TYPE IN('SINGLE', 'TWIN', 'QUEEN', 'EXECUTIVE', 'SUITE')),
	ROOM_QUANTITY INTEGER NOT NULL,
	ROOM_PRICE DECIMAL NOT NULL,
	ROOM_DISCOUNT DOUBLE DEFAULT NULL,
	ROOM_DISCOUNTFROM DATE DEFAULT NULL,
	ROOM_DISCOUNTTO DATE DEFAULT NULL,
	HOTEL_ID INTEGER NOT NULL,
	
	FOREIGN KEY (HOTEL_ID) REFERENCES TBL_HOTELS(HOTEL_ID)
);

CREATE TABLE TBL_ROOMS_SPECIFIC(
	ROOM_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	PRIMARY KEY(ROOM_ID),
	ROOM_NO INTEGER NOT NULL,
	ROOM_TYPE_SPECIFIC VARCHAR(10) NOT NULL CHECK (ROOM_TYPE_SPECIFIC IN('SINGLE', 'TWIN', 'QUEEN', 'EXECUTIVE', 'SUITE')),
	ROOM_CONDITION VARCHAR(20) NOT NULL CHECK (ROOM_CONDITION IN('AVAILABLE', 'OCCUPIED', 'MAINTENANCE')),
	HOTEL_ID INTEGER NOT NULL,
	
	FOREIGN KEY (HOTEL_ID) REFERENCES TBL_HOTELS(HOTEL_ID)
	--FOREIGN KEY (ROOM_TYPE_SPECIFIC) REFERENCES TBL_ROOMS_GENERAL(ROOM_TYPE)
);

CREATE TABLE TBL_BOOKINGS(
	BOOKING_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	PRIMARY KEY(BOOKING_ID),
	CUSTOMER_ID INTEGER NOT NULL,
	HOTEL_ID INTEGER NOT NULL,
	PIN INTEGER NOT NULL,
	ROOM_TYPE VARCHAR(10) NOT NULL CHECK (ROOM_TYPE IN('SINGLE', 'TWIN', 'QUEEN', 'EXECUTIVE', 'SUITE')),
	ROOM_QUANTITY INTEGER NOT NULL,
	EXTRA_BED INTEGER NOT NULL,
	TOTALPRICE DECIMAL NOT NULL,
	FROMDATE DATE DEFAULT NULL,
	TODATE DATE DEFAULT NULL,
	DETAILS LONG VARCHAR NOT NULL,
	
	FOREIGN KEY (CUSTOMER_ID) REFERENCES TBL_USERS(USER_ID),
	FOREIGN KEY (HOTEL_ID) REFERENCES TBL_HOTELS(HOTEL_ID)
	--FOREIGN KEY (ROOM_TYPE) REFERENCES TBL_ROOMS_GENERAL(ROOM_TYPE)
);

CREATE TABLE TBL_PEAK(
	PEAK_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	PRIMARY KEY(PEAK_ID),
	ROOM_TYPE VARCHAR(10) NOT NULL CHECK (ROOM_TYPE IN('SINGLE', 'TWIN', 'QUEEN', 'EXECUTIVE', 'SUITE')),
	ROOM_PEAK DOUBLE DEFAULT NULL,
	ROOM_PEAKFROM DATE DEFAULT NULL,
	ROOM_PEAKTO DATE DEFAULT NULL
);

CREATE TABLE TBL_PIN(
	PIN INTEGER NOT NULL,
	PRIMARY KEY(PIN),
	URL LONG VARCHAR NOT NULL
);