SELECT * FROM TBL_USERS;
SELECT * FROM TBL_HOTELS;
SELECT * FROM TBL_ROOMS_GENERAL;
SELECT * FROM TBL_ROOMS_SPECIFIC;
SELECT * FROM TBL_BOOKINGS;
SELECT * FROM TBL_PEAK;
SELECT * FROM TBL_PIN;

DELETE FROM TBL_PIN;
DELETE FROM TBL_HOTELS;
DELETE FROM TBL_ROOMS_GENERAL;
DELETE FROM TBL_ROOMS_SPECIFIC;
DELETE FROM TBL_BOOKINGS;
DELETE FROM TBL_PEAK;
DELETE FROM TBL_USERS;


--DELETE BOOKING
SELECT * FROM TBL_BOOKINGS WHERE CUSTOMER_ID = 4;


--SELECT PIN
SELECT PIN FROM TBL_PIN WHERE CAST(URL AS VARCHAR(128)) = 'http://localhost:8080/HotelInn/ServletControl?control=URL&ID=-792e3577:145d1a04933:-8000';


--INSERT NEW USER
INSERT INTO TBL_USERS (SURNAME, OTHERNAME, ROLE, USERNAME, PASSWORD, EMAIL, DETAILS) VALUES
('ABC', 'ABC', 'CUSTOMER', 'ABC', 'ABC', 'ABC@ABC.COM', 'ABCDEFG');

--GET USERID
SELECT MAX(USER_ID) AS USER_ID FROM TBL_USERS;

--GET BOOKINGID
SELECT MAX(BOOKING_ID) AS BOOKING_ID FROM TBL_BOOKINGS;

SELECT COUNT(*) FROM TBL_ROOMS_GENERAL WHERE ROOM_TYPE = 'SINGLE';

--TEST
SELECT ROOM_QUANTITY
FROM TBL_ROOMS_GENERAL
WHERE HOTEL_ID = 1
AND ROOM_TYPE = 'SINGLE';

--PEAK PRICE
SELECT TBL_PEAK.ROOM_PEAK, TBL_PEAK.ROOM_PEAKFROM, TBL_PEAK.ROOM_PEAKTO
FROM TBL_PEAK
WHERE ((TBL_PEAK.ROOM_PEAKFROM <= '2014-09-10' AND TBL_PEAK.ROOM_PEAKTO >= '2014-09-10')
OR (TBL_PEAK.ROOM_PEAKFROM <= '2014-09-13' AND TBL_PEAK.ROOM_PEAKTO >= '2014-09-13'))
AND (TBL_PEAK.ROOM_TYPE = 'SINGLE');

--DISCOUNT PRICE
SELECT TBL_ROOMS_GENERAL.ROOM_DISCOUNT, TBL_ROOMS_GENERAL.ROOM_DISCOUNTFROM, TBL_ROOMS_GENERAL.ROOM_DISCOUNTTO
FROM TBL_ROOMS_GENERAL
WHERE ((TBL_ROOMS_GENERAL.ROOM_DISCOUNTFROM <= '2014-09-10' AND TBL_ROOMS_GENERAL.ROOM_DISCOUNTTO >= '2014-09-10')
OR (TBL_ROOMS_GENERAL.ROOM_DISCOUNTFROM <= '2014-09-13' AND TBL_ROOMS_GENERAL.ROOM_DISCOUNTTO >= '2014-09-13'))
AND (TBL_ROOMS_GENERAL.HOTEL_ID = 1)
AND (TBL_ROOMS_GENERAL.ROOM_TYPE = 'SINGLE');

--NORMAL PRICE
SELECT TBL_ROOMS_GENERAL.ROOM_PRICE
FROM TBL_ROOMS_GENERAL
WHERE TBL_ROOMS_GENERAL.HOTEL_ID = 1
AND TBL_ROOMS_GENERAL.ROOM_TYPE = 'SINGLE';

--BOOKED QUANTITY
SELECT TBL_BOOKINGS.ROOM_QUANTITY AS QUANTITY
FROM TBL_BOOKINGS
WHERE ((TBL_BOOKINGS.FROMDATE <= '2014-09-10' AND TBL_BOOKINGS.TODATE >= '2014-09-10')
OR (TBL_BOOKINGS.FROMDATE <= '2014-09-13' AND TBL_BOOKINGS.TODATE >= '2014-09-13'))
AND (TBL_BOOKINGS.HOTEL_ID = 1)
AND (TBL_BOOKINGS.ROOM_TYPE = 'SINGLE');

--TOTAL QUANTITY
SELECT TBL_ROOMS_GENERAL.ROOM_TYPE, TBL_ROOMS_GENERAL.ROOM_QUANTITY
FROM TBL_ROOMS_GENERAL
WHERE TBL_ROOMS_GENERAL.HOTEL_ID = 1
AND TBL_ROOMS_GENERAL.ROOM_TYPE = 'SINGLE';

-- HOTELID
SELECT TBL_HOTELS.HOTEL_ID
FROM TBL_HOTELS
WHERE TBL_HOTELS.CITY = 'Canberra';

-- TOTAL QUANTITY
SELECT TBL_ROOMS_GENERAL.ROOM_TYPE, TBL_ROOMS_GENERAL.ROOM_QUANTITY, TBL_ROOMS_GENERAL.ROOM_PRICE,
	   TBL_ROOMS_GENERAL.ROOM_DISCOUNT, TBL_ROOMS_GENERAL.ROOM_DISCOUNTFROM, TBL_ROOMS_GENERAL.ROOM_DISCOUNTTO
FROM TBL_ROOMS_GENERAL
WHERE TBL_ROOMS_GENERAL.HOTEL_ID = 1;


-- AVAIABLE QUANTITY
SELECT TBL_ROOMS_SPECIFIC.ROOM_TYPE_SPECIFIC AS ROOM_TYPE, COUNT(TBL_ROOMS_SPECIFIC.ROOM_TYPE_SPECIFIC) AS QUANTITY
FROM TBL_ROOMS_SPECIFIC
WHERE TBL_ROOMS_SPECIFIC.HOTEL_ID = 1
AND TBL_ROOMS_SPECIFIC.ROOM_CONDITION = 'AVAIABLE'
GROUP BY TBL_ROOMS_SPECIFIC.ROOM_TYPE_SPECIFIC;

-- BOOKING QUANTITY
SELECT TBL_BOOKINGS.ROOM_TYPE, TBL_BOOKINGS.ROOM_QUANTITY, TBL_BOOKINGS.FROMDATE, TBL_BOOKINGS.TODATE
FROM TBL_BOOKINGS
WHERE TBL_BOOKINGS.HOTEL_ID = 1;